import json
from urllib.request import Request, urlopen
from w3lib.url import canonicalize_url
import requests
import re
from bs4 import BeautifulSoup
from PIL import Image
import io
import json
import time
import logging

DEFAULT_HEADERS = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11',
       'Accept': 'image/gif,image/apng,image/avif,image/webp,image/png,image/jpeg,text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
       'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
       'Accept-Encoding': 'none',
       'Accept-Language': 'en-US,en;q=0.8',
       'Connection': 'keep-alive'}
"""Headers must be sent to most websites to say: "I'm not a bot."""

def download(url: str, headers=None) -> bytes:
    """
    Downloads bytes from the web.

    Args:
        url: The url to download data from.

    Returns:
        A bytes object.
    """
    url = canonicalize_url(url)
    logging.debug("Downloading " + url)

    if headers:
        req = Request(url, headers=headers)
    else:
        req = Request(url)

    with urlopen(req) as response:
        result = response.read()
    return result

def download_soup(url: str, headers=None) -> BeautifulSoup:
    """
    Downloads a BeautifulSoup object for HTML from the web.

    Args:
        url: The url to download the HTML from.

    Returns:
        A BeautifulSoup object for HTML parsing.
    """
    result = download(url, headers)
    decoded = result.decode("utf-8")
    return BeautifulSoup(decoded,  features="html.parser")

def download_image(url: str, headers=None) -> Image.Image:
    """
    Downloads an image from the web.

    Args:
        url: The url to download the image from.
    Returns:
        A Pillow Image object which can be saved.
    """
    result = download(url, headers)
    return Image.open(io.BytesIO(result))

def get_vqd(query) -> str:
    """
    Obtains the VQD key from DuckDuckGo
     
    The VQD key is required for image 
    search requests. Just put the query
    for the image request into here
    to use the key later.

    Args:
        query: The search query. This should be the same 
            as the search query for the image search request.
    
    """

    res = requests.post('https://duckduckgo.com/', data={'q': query})
    searchObj = re.search(r'vqd=\"(.+?)\"', res.text)
    
    if not searchObj:
        raise Exception("VQD variable was not present.")

    return searchObj.group(1)

class DuckImage:
    def __init__(self, encoding: str, width: int, height: int, thumbnail: str, url: str, title: str, image: str):
        self.encoding = encoding
        """The image format."""
        self.width = width
        self.height = height
        self.thumbnail = thumbnail
        """The thumbnail URL generated by Bing. Provides a smaller version 
        of the original image and is recommended in all cases."""
        self.url = url
        """This is NOT the image URL, but the URL of the site 
        the image came from, e.g. a news source. For the image,
        use `thumbnail` or `image` for an image URL."""
        self.title = title
        """This is the text underneath the image when previewing."""
        self.image = image
        """The original image URL. Not recommended as this can be 
        a very large download. Moreover, this link can fail if the
        incorrect headers are provided. Unless you REALLY need to
        use the original image, use `thumbnail` instead."""

    def __repr__(self) -> str:
        return f"DuckImage{self.__dict__}"

    def download(self, original: bool = False) -> Image.Image:
        """
        Downloads the image as a PIL image.

        Either downloads the generated thumbnail from Bing,
        or the original. Headers are not sent, and many sites
        will deny access to their URLs. You'll have to write
        your own image download method for properly obtaining
        the original. Otherwise, downloading the thumbnail
        rarely fails.
        
        Args:
            original: Whether or not to download the original image. 
                False is recommended.
        
        Returns:
            An image from either chosen URL.
        """
        if original:
            return download_image(self.image)
        else:
            return download_image(self.thumbnail)

class DuckExternalLink:
    """Container for link information."""
    def __init__(self, url: str, title: str, snippet: str = ''):
        self.url = url
        self.title = title
        self.snippet = snippet
        """A preview of the page"""

    def soup(self, headers=None) -> BeautifulSoup:
        """Downloads and parses the HTML from the external link."""
        return download_soup(self.url, headers)

    def text(self, headers=None) -> str:
        """Downloads text from the external link."""
        return self.soup(headers).text

class PageRefusalException(Exception):
    """Exception for when the client is detected as a bot."""
    def __init__(self, text: str):
        super().__init__(text)

def web_search(query, delay: int = 1) -> list[DuckExternalLink]:
    """
    Performs a web search using DuckDuckGo and returns the result list.

    Each list item contains a `url`, `title`, and `snippet`.

    Args:
        query: The search query. A search of "cat facts" will return 
            web pages with cat facts.
        delay: A fixed delay before the request is made to prevent getting blocked.
            The search tests were actually failing without this delay.

    Returns:
        A list of links with titles and descriptions
    """
    # DuckDuckGo refuses large numbers of requests, so this delay tries to prevent that
    time.sleep(delay)

    # The search is made directly with a GET request
    url = f'http://duckduckgo.com/html/?q={query}'
    listing = download_soup(url, DEFAULT_HEADERS)

    containers = listing.find_all('div', {'class': re.compile('links_main*')})
    if len(containers) == 0:
        raise PageRefusalException("Client was detected as a bot. Either too many requests were sent, the search failed, or invalid headers were sent.")

    results = []
    # Every result in the list is in a `div` of class "links_main"
    # So, a "links_main" class is a container for the title, url, icon, and snippet.
    for links in containers:
        # The title has the class "result__a" for some reason
        title_obj = links.find('a', {'class': re.compile('result__a')})
        assert title_obj != None
        # Both the text and URL are taken from the title link
        link_title = title_obj.text
        link_url = str(title_obj.get('href'))
        assert type(link_url) == str
        # The snippet makes more sense
        snippet_obj = links.find('a', {'class': re.compile('result__snippet')})
        link_snippet = ''
        # In case the snippet is missing (which may never be the case),
        # the actual snippet is only assigned if the snippet was present.
        if snippet_obj != None:
            link_snippet = snippet_obj.text
        # The three variables are put into a container class
        results.append(DuckExternalLink(link_url, link_title, link_snippet))
    return results

def _validate_flag_enum(flag, valid: tuple) -> str:
    flag = str(flag).title()
    if flag != 'any':
        if type(flag) != str:
            raise TypeError(f"Argument 'time' has incorrect type \"{type(flag)}\", should be str.")
        if flag not in valid:
            raise ValueError(f"Time \"{flag}\" is not valid. Should be one of: {valid}")
    return flag

def image_search(query, hide_ai_images: bool = True, time_range: str = 'Any', size: str = 'Any', layout: str = 'Any', locale='us-en', delay: int = 1) -> list[DuckImage]:
    """
    Search the DuckDuckGo image database.

    This sends back a variable number of images. It
    can be less than twenty, or it can be over thirty.
    Keep in mind, the images must be manually downloaded
    afterward. For example:

    ```
    results = image_search('cat')
    img = results[0].download()
    ``` 

    Args:
        query: The search query. "Cat" will yield cat images.
        hide_ai_images: Whether or not to try hiding some AI images.
        time_range: 
            Time range of allowed results in the past day, month, or week.
            Allowed values are 'Any', 'Day', 'Week', 'Month'.
        size: 
            The estimated size of the images returned.
            Allowed values are 'Any', 'Small', 'Medium', 'Large', 'Wallpaper'.
        layout:
            The shape of the image results
            Allowed values are 'Any', 'Square', 'Tall', 'Wide'.
        locale: Changes the results to be catered toward a different region.
            Make sure to enter a valid ISO 639 language code preceded
            by a valid ISO 3166 code.
             
            Not all languages/regions are supported by search engines.
            This field is untested and may do nothing right now.
        delay: A fixed delay before the request is made to prevent getting blocked.
    """
    # DuckDuckGo refuses large numbers of requests, this manages them.
    time.sleep(delay)

    # This is required for the request
    vqd = get_vqd(query)

    # Flags are assembled directly in a string
    flags = f'hide_ai_images:{int(hide_ai_images)}'

    time_range = _validate_flag_enum(time_range, ('Any', 'Day', 'Week', 'Month'))
    if time_range != 'Any':
        flags += ',time:{time}'

    size = _validate_flag_enum(size, ('Any', 'Small', 'Medium', 'Large', 'Wallpaper'))
    if size != 'Any':
        flags += ',size:{size}'

    # layout:Square
    layout = _validate_flag_enum(layout, ('Any', 'Square', 'Tall', 'Wide'))
    if layout != 'Any':
            flags += ',layout:{layout}'

    # Parameters sent with the POST request
    params = (
        ('l', locale), # l : language/region
        ('o', 'json'), # o : probably the desired response format?
        ('q', query), # q : search query
        ('vqd', vqd), # vqd : honestly don't know
        ('f', flags), # f : filters (key:value,)
        ('p', '1'), # ???
        ('v7exp', 'a'), # ???
    )

    # Attempts downloading the data
    res = requests.get(
        'https://duckduckgo.com/i.js', 
        headers=DEFAULT_HEADERS, 
        params=params
        )
    data = json.loads(res.text);

    # Reassembles the dict list as an array of DuckImages
    items = []
    for item in data['results']:
        items.append(
            DuckImage(
                item['encoding_format'], 
                int(item['width']), 
                int(item['height']), 
                item['thumbnail'], 
                item['url'], 
                item['title'], 
                item['image']
                )
            )
    return items
