import json
import requests
import re
from bs4 import BeautifulSoup
from PIL import Image
import json
import time
import duckdunk.headers as headers
from duckdunk.download import download_image, download_soup
import duckdunk.util as util

class DuckImage:
    def __init__(self, encoding: str, width: int, height: int, thumbnail: str, url: str, title: str, image: str):
        self.encoding = encoding
        """The image format."""
        self.width = width
        self.height = height
        self.thumbnail = thumbnail
        """The thumbnail URL generated by Bing. Provides a smaller version 
        of the original image and is recommended in all cases."""
        self.url = url
        """This is NOT the image URL, but the URL of the site 
        the image came from, e.g. a news source. For the image,
        use `thumbnail` or `image` for an image URL."""
        self.title = title
        """This is the text underneath the image when previewing."""
        self.image = image
        """The original image URL. Not recommended as this can be 
        a very large download. Moreover, this link can fail if the
        incorrect headers are provided. Unless you REALLY need to
        use the original image, use `thumbnail` instead."""

    def __repr__(self) -> str:
        return f"DuckImage{self.__dict__}"

    def download(self, original: bool = False) -> Image.Image:
        """
        Downloads the image as a PIL image.

        Either downloads the generated thumbnail from Bing,
        or the original. Headers are not sent, and many sites
        will deny access to their URLs. You'll have to write
        your own image download method for properly obtaining
        the original. Otherwise, downloading the thumbnail
        rarely fails.
        
        Args:
            original: Whether or not to download the original image. 
                False is recommended.
        
        Returns:
            An image from either chosen URL.
        """
        if original:
            return download_image(self.image)
        else:
            return download_image(self.thumbnail)

class DuckExternalLink:
    """Container for link information."""
    def __init__(self, url: str, title: str, snippet: str = ''):
        self.url = url
        self.title = title
        self.snippet = snippet
        """A preview of the page"""

    def soup(self, headers=None) -> BeautifulSoup:
        """Downloads and parses the HTML from the external link."""
        return download_soup(self.url, headers)

    def text(self, headers=None) -> str:
        """Downloads text from the external link."""
        return self.soup(headers).text

class PageRefusalException(Exception):
    """Exception for when the client is detected as a bot."""
    def __init__(self, text: str):
        super().__init__(text)

def _get_all_tjs(text) -> dict[str, str]:
    """Get all variables sent to DuckDuckGo's t.js"""
    return util.extract_dict(text, r'/t\.js\?', r'></script>', '&', '=')

def _get_all_javascript_var(text) -> dict[str, str]:
    """Get unlabeled variables from DuckDuckGo"""
    return util.extract_dict(
        text, r'<script type="text/javascript">var ', r';function', ',', '=')

def _get_djs_params(query) -> list[tuple[str, str]]:
    """Obtains the variables required to invoke d.js on DuckDuckGo"""
    res = requests.post('https://duckduckgo.com/', data={'q': query})
    text = res.text
    tjs = _get_all_tjs(text)
    js = _get_all_javascript_var(text)
    return [
        ('q', tjs['q']),
        ('t', 'D'), # tjs['t'] this variable is not always present
        ('kl', tjs['l']),
        ('l', tjs['l']),
        ('s', tjs['s']),
        ('a', js['ra']),
        ('ct', tjs['ct']),
        ('vqd', js['vqd']),
        ('bing_market', tjs['bing_market']),
        ('p_ent', tjs['p_ent']),
        ('ex', tjs['ex']),
        ('dp', tjs['dp']),
        ('perf_id', tjs['perf_id']),
        ('parent_perf_id', tjs['parent_perf_id']),
        ('perf_sampled', tjs['perf_sampled']),
        ('host_region', tjs['host_region']),
        ('sp', "0"),# tjs['sp']), These following variables return empty instead of their correct values
        ('dfrsp', "1"), # tjs['dfrsp']),
        ('wrap', "1"),# tjs['wrap']),
        ('aps', "0"), # tjs['aps']),
        ('biaexp', 'b'),
        ('desktopadclickablecontentexp', 'b'),
        ('discussionsciexp', 'b'),
        ('litexp', 'a'),
        ('msvrtexp', 'b'),
        ('searchbarexp', 'b'),
        ('weatherexp', 'b'),
        ('you_news_verticalexp', 'b'),
    ]

def _get_tjs_params(query) -> list[tuple[str, str]]:
    """Obtains the variables required to invoke t.js on DuckDuckGo"""
    res = requests.post('https://duckduckgo.com/', data={'q': query})
    text = res.text
    tjs = _get_all_tjs(text)
    js = _get_all_javascript_var(text)
    return [
        ('q', tjs['q']),
        ('t', 'D'), # tjs['t']
        ('l', tjs['l']),
        ('s', tjs['s']),
        ('a', js['ra']),
        ('ct', tjs['ct']),
        ('bing_market', tjs['bing_market']),
        ('p_ent', tjs['p_ent']),
        ('ex', tjs['ex']),
        ('dp', tjs['dp']),
        ('perf_id', tjs['perf_id']),
        ('parent_perf_id', tjs['parent_perf_id']),
        ('perf_sampled', tjs['perf_sampled']),
        ('host_region', tjs['host_region']),
        ('sp', "0"), # tjs['sp']),
        ('baa', '1'),
        ('aps', "0"), # tjs['aps']),
        ('biaexp', 'b'),
        ('desktopadclickablecontentexp', 'b'),
        ('discussionsciexp', 'b'),
        ('litexp', 'a'),
        ('msvrtexp', 'b'),
        ('searchbarexp', 'b'),
        ('weatherexp', 'b'),
        ('you_news_verticalexp', 'b'),
    ]

def resolve_duckduckgo(query: str) -> str:
    res = requests.post('https://duckduckgo.com/', data={'q': query}, headers=headers.DEFAULT)
    return res.text

def _exp_web_search(query, delay: int = 1):
    """Maybe new web search method. For some reason the returned JavaScript has empty values."""
    params = _get_djs_params(query)
    time.sleep(0.2)
    res = requests.get(
            'https://duckduckgo.com/d.js', 
            headers=headers.DUCKDUCKGO_WEB_SEARCH, 
            params=params
            )
    return res.text

def web_search(query, delay: int = 1) -> list[DuckExternalLink]:
    """
    Performs a web search using DuckDuckGo and returns the result list.

    Each list item contains a `url`, `title`, and `snippet`.

    Args:
        query: The search query. A search of "cat facts" will return 
            web pages with cat facts.
        delay: A fixed delay before the request is made to prevent getting blocked.
            The search tests were actually failing without this delay.

    Returns:
        A list of links with titles and descriptions
    """
    # DuckDuckGo refuses large numbers of requests, so this delay tries to prevent that
    time.sleep(delay)

    # The search is made directly with a GET request
    url = f'http://duckduckgo.com/html/?q={query}'
    listing = download_soup(url, headers.DEFAULT)

    containers = listing.find_all('div', {'class': re.compile('links_main*')})
    if len(containers) == 0:
        raise PageRefusalException("Client was detected as a bot. Either too many requests were sent, the search failed, or invalid headers were sent.")

    results = []
    # Every result in the list is in a `div` of class "links_main"
    # So, a "links_main" class is a container for the title, url, icon, and snippet.
    for links in containers:
        # The title has the class "result__a" for some reason
        title_obj = links.find('a', {'class': re.compile('result__a')})
        assert title_obj != None
        # Both the text and URL are taken from the title link
        link_title = title_obj.text
        link_url = str(title_obj.get('href'))
        assert type(link_url) == str
        # The snippet makes more sense
        snippet_obj = links.find('a', {'class': re.compile('result__snippet')})
        link_snippet = ''
        # In case the snippet is missing (which may never be the case),
        # the actual snippet is only assigned if the snippet was present.
        if snippet_obj != None:
            link_snippet = snippet_obj.text
        # The three variables are put into a container class
        results.append(DuckExternalLink(link_url, link_title, link_snippet))
    return results

def _validate_flag_enum(flag, valid: tuple) -> str:
    flag = str(flag).title()
    if flag != 'any':
        if type(flag) != str:
            raise TypeError(f"Argument has incorrect type \"{type(flag)}\", should be str.")
        if flag not in valid:
            raise ValueError(f"Time \"{flag}\" is not valid. Should be one of: {valid}")
    return flag

def _try_add_string_flag(key, flag, valid: tuple):
    flag = _validate_flag_enum(flag, valid)
    if flag != 'Any':
        return f',{key}:{flag}'
    return ''

def image_search(query, hide_ai_images: bool = True, time_range: str = 'Any', size: str = 'Any', layout: str = 'Any', locale='us-en', delay: int = 1) -> list[DuckImage]:
    """
    Search the DuckDuckGo image database.

    This sends back a variable number of images. It
    can be less than twenty, or it can be over thirty.
    Keep in mind, the images must be manually downloaded
    afterward. For example:

    ```
    results = image_search('cat')
    img = results[0].download()
    ``` 

    Args:
        query: The search query. "Cat" will yield cat images.
        hide_ai_images: Whether or not to try hiding some AI images.
        time_range: 
            Time range of allowed results in the past day, month, or week.
            Allowed values are 'Any', 'Day', 'Week', 'Month'.
        size: 
            The estimated size of the images returned.
            Allowed values are 'Any', 'Small', 'Medium', 'Large', 'Wallpaper'.
        layout:
            The shape of the image results
            Allowed values are 'Any', 'Square', 'Tall', 'Wide'.
        locale: Changes the results to be catered toward a different region.
            Make sure to enter a valid ISO 639 language code preceded
            by a valid ISO 3166 code.
             
            Not all languages/regions are supported by search engines.
            This field is untested and may do nothing right now.
        delay: A fixed delay before the request is made to prevent getting blocked.
    """
    # Obtain search variables for unofficial API calls 
    raw_data = resolve_duckduckgo(query)
    # tjs = _get_all_tjs(raw_data)
    js = _get_all_javascript_var(raw_data)
    
    # DuckDuckGo refuses large numbers of requests, this manages them.
    time.sleep(delay)

    # Flags are assembled directly in a string
    flags = f'hide_ai_images:{int(hide_ai_images)}'

    # Add any valid flags that aren't "Any"
    flags += _try_add_string_flag('time', time_range, ('Any', 'Day', 'Week', 'Month'))
    flags += _try_add_string_flag('size', size, ('Any', 'Small', 'Medium', 'Large', 'Wallpaper'))
    flags += _try_add_string_flag('layout', layout, ('Any', 'Square', 'Tall', 'Wide'))

    # Parameters sent with the POST request
    params = (
        ('o', 'json'), # o : probably the desired response format?
        ('q', query), # q : search query
        ('l', locale), # l : language/region
        ('p', '1'),
        ('vqd', js['vqd']), # The search hash
        ('ct', js['ct']), # country
        # ('dp', tjs['dp']),
        ('f', flags), # f : filters (key:value,)
        # ('bpia', '1'),
        # ('a', 'h_'),
        # ('v7exp', 'a'), 
    )

    # Attempts downloading the data
    res = requests.get(
        'https://duckduckgo.com/i.js', 
        headers=headers.DUCKDUCKGO_IMAGE_SEARCH, 
        params=params
        )
    data = json.loads(res.text);

    # Reassembles the dict list as an array of DuckImage objects
    items = []
    for item in data['results']:
        items.append(
            DuckImage(
                item['encoding_format'], 
                int(item['width']), 
                int(item['height']), 
                item['thumbnail'], 
                item['url'], 
                item['title'], 
                item['image']
                )
            )
    return items
