name: Unit Tests

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Test with pytest
        run: |
          pip install -r requirements.txt
          pip install coverage
          coverage run -m unittest discover -s "./tests/unit"
          coverage report -m > output/test/.coverage_report.txt
          coverage xml .coverage-report.xml

      - name: Upload coverage report XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-xml
          path: output/test/.coverage-report.xml
